name: After saving wordpress

on: # トリガー
  repository_dispatch:
    type: after_saving_wordpress
  push:
    branches:
      - main
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.x"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Set environment variables for staging
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "WP_API_KEY=${{ secrets.STAGING_WP_API_KEY }}" >> $GITHUB_ENV
          echo "SITE_DOMAIN=${{ secrets.STAGING_SITE_DOMAIN }}" >> $GITHUB_ENV
          echo "FTP_SERVER=${{ secrets.STAGING_FTP_SERVER }}" >> $GITHUB_ENV
          echo "FTP_USERNAME=${{ secrets.STAGING_FTP_USERNAME }}" >> $GITHUB_ENV
          echo "FTP_PASSWORD=${{ secrets.STAGING_FTP_PASSWORD }}" >> $GITHUB_ENV
          echo "DEPLOY_DIR=${{ secrets.STAGING_DEPLOY_DIR }}" >> $GITHUB_ENV
      - name: Set environment variables for production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "WP_API_KEY=${{ secrets.PROD_WP_API_KEY }}" >> $GITHUB_ENV
          echo "SITE_DOMAIN=${{ secrets.PROD_SITE_DOMAIN }}" >> $GITHUB_ENV
          echo "FTP_SERVER=${{ secrets.PROD_FTP_SERVER }}" >> $GITHUB_ENV
          echo "FTP_USERNAME=${{ secrets.PROD_FTP_USERNAME }}" >> $GITHUB_ENV
          echo "FTP_PASSWORD=${{ secrets.PROD_FTP_PASSWORD }}" >> $GITHUB_ENV
          echo "DEPLOY_DIR=${{ secrets.PROD_DEPLOY_DIR }}" >> $GITHUB_ENV

      # - name: Set API_KEY environment variable
      # run: echo "WP_API_KEY=${{ env.WP_API_KEY }}" >> $GITHUB_ENV
      - name: Verify WP_API_KEY
        run: |
          if [ -z "$WP_API_KEY" ]; then
            echo "WP_API_KEY is not set"
          else
            echo "WP_API_KEY is set"
          fi
      - name: npm install # パッケージをインストール
        run: npm install
      - name: generate # SSG
        #run: npm run generate #下記を追記したのでコメントアウト
        run: NODE_OPTIONS="--max-old-space-size=8192" npm run generate #メモリ上限を8Gに増やす
        env:
          WP_API_KEY: ${{ env.WP_API_KEY }}
          SITE_DOMAIN: ${{ env.SITE_DOMAIN }}
        #continue-on-error: true #エラーをスルー

      - name: List output files
        run: ls -la dist/ # ファイルリストを表示

      - name: Deploy via FTP⏫
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ env.FTP_SERVER }} # FTPサーバのホスト
          username: ${{ env.FTP_USERNAME }} # FTPサーバのアカウント名
          password: ${{ env.FTP_PASSWORD }} # FTPサーバのパスワード
          server-dir: ${{ env.DEPLOY_DIR }} # アップロード先のリモートパス
          local-dir: ./dist/ # ローカルのアップロードしたいフォルダのパス
          useDiff: false #全ファイルアップする設定。trueにすれば差分だけアップして軽いが、wordpressからの更新はデータのみの更新なのでファイルはアップされない
          #dangerous-clean-slate: true #全ファイルアップ前に削除　すごい時間かかる
